seznam/ima

package-lock.json, packages/create-ima-app/examples/feed/build.js, packages/create-ima-app/examples/feed/config/bind.js, packages/create-ima-app/examples/feed/mock/MockHttpAgent.js, packages/create-ima-app/examples/feed/model/categoryList/CategoryListService.js, packages/create-ima-app/examples/hello/build.js, packages/create-ima-app/examples/hello/config/bind.js, packages/create-ima-app/examples/todos/build.js, packages/create-ima-app/examples/todos/config/bind.js
- Client/server build
- new way to register $Utils (files bind.js)
=> Create-ima-app examples

packages/create-ima-app/bin/create-ima-app.js, packages/create-ima-app/package-lock.json, packages/create-ima-app/package.json, packages/create-ima-app/scripts/create.js, packages/create-ima-app/utils/utils.js
- Added check for min/max node version before installation
- Git repository is now initialized only if git is present on the system
=> feat: added dependency check to create-ima-app

packages/core/src/page/manager/AbstractPageManager.js, packages/core/src/page/manager/__tests__/AbstractPageManagerSpec.js, packages/core/src/page/renderer/ClientPageRenderer.js, packages/core/src/page/renderer/PageRenderer.js, packages/core/src/page/renderer/__tests__/ClientPageRendererSpec.js
Page state is cleared after new state is know after page transition
=> refactor: 💡 page state clearing

docs/docs/extensions.md
- Added $dependencies to Extension implementation, otherwise it wouldn't work properly.
=> docs: Extension example fix

docs/tutorial/adding-some-state.md, docs/tutorial/fetching-the-data-from-the-server.md, docs/tutorial/introduction.md, docs/tutorial/static-view.md, docs/tutorial/writing-posts.md
Corrections to the IMA tutorial, tested on IMA17. Mostly code snippet formatting (so Beautifier doesn't complain right away when copy-pasting), some copy editing, and a few outdated mentions.
=> Tutorial update

packages/core/src/page/renderer/AbstractPageRenderer.js, packages/core/src/page/renderer/ViewAdapter.js, packages/core/src/page/renderer/__tests__/AbstractPageRendererSpec.js
viewAdapter for some cases did not set state from props
=> fix: 🐛 viewAdapter set state from props

docs/docs/devtools-introduction.md, packages/devtools-scripts/package-lock.json, packages/devtools-scripts/package.json, packages/devtools/manifest.json, packages/devtools/package-lock.json, packages/devtools/src/components/molecule/search/Search.jsx, packages/devtools/src/components/molecule/search/__tests__/__snapshots__/SearchSpec.jsx.snap
- Moved clear button out of the 'more options' menu group, to be easily accessible.
- Removed unused permissions from chrome manifest.json
=> fix: 🐛 Removed unused permissions from devtools manifest.json

packages/create-ima-app/bin/create-ima-app.js, packages/create-ima-app/examples/hello/environment.js, packages/server/lib/clientApp.js, packages/server/lib/instanceRecycler.js, utils/benchmark/app/environment.js
The server needs protection for overloading for black listed user agents.
=> Blacklist concurrency

packages/core/src/page/renderer/ClientPageRenderer.js
=> fix: 🐛 $IMA.$PageRenderer.unmounted call on page unmount

packages/devtools/package.json
Removed unnecessary test and install tasks run when publishing chrome
devtools from CI.
=> ci: 🎡 Removed unnecessary test and install tasks

README.md
- fixed some grammar mistakes
- added commands for yarn
=> Fixed grammar mistakes in readme

docs/_data/docs.json, docs/_sass/rouge-github.scss, docs/docs.md, docs/docs/routing.md, packages/core/src/main.js, packages/core/src/page/manager/AbstractPageManager.js, packages/core/src/page/manager/PageManager.js, packages/core/src/router/AbstractRoute.js, packages/core/src/router/AbstractRouter.js, packages/core/src/router/DynamicRoute.js, packages/core/src/router/Events.js, packages/core/src/router/RouteFactory.js, packages/core/src/router/Router.js, packages/core/src/router/StaticRoute.js, packages/core/src/router/__tests__/AbstractRouteSpec.js, packages/core/src/router/__tests__/DynamicRouteSpec.js, packages/core/src/router/__tests__/StaticRouteSpec.js
StaticRoute (previously Route) has the same functionality as previous
Route. Hoewere DynamicRoute allows you to override methods for parsing
url params and creating path from params with custom RegExp matcher.
This allows you to create dynamic route matchers to match all possible
path schapes that previously wasn't possible.
=> feat: 🎸 Static and Dynamic Routes

.changeset/tough-days-pump.md, .changeset/weak-peas-fetch.md, docs/cli/compiler-features.md, package-lock.json, packages/core/src/http/HttpProxy.ts, packages/error-overlay/package.json, packages/error-overlay/src/App.tsx, packages/error-overlay/src/app.less, packages/error-overlay/src/components/errorParams/ErrorParams.tsx, packages/error-overlay/src/components/errorParams/errorParams.less, packages/error-overlay/src/hooks/useConnect.ts, packages/error-overlay/src/types.ts, packages/error-overlay/src/utils/prismUtils.ts, packages/server/lib/factory/devErrorPageFactory.js, packages/server/lib/factory/loggerFactory.js
- Fixed error params mergin in http proxy
- Added support for new error params view in error overlay and console
=> Proxy error params fix

.changeset/afraid-carpets-hear.md, packages/core/src/router/AbstractRoute.ts
=> Made getView and getController method sync

.changeset/strong-doors-check.md, packages/server/lib/factory/hooksFactory.js
- context.app is instance of ima App or undefined for static mode
=> Fix server

.changeset/polite-onions-approve.md, packages/server/lib/factory/__tests__/serverAppFactorySpec.js, packages/server/lib/factory/hooksFactory.js
=> Revert "Server redirect"

.changeset/four-cheetahs-warn.md, .changeset/ten-dryers-glow.md, packages/server/lib/factory/IMAInternalFactory.js, packages/server/lib/factory/__tests__/serverAppFactorySpec.js, packages/server/lib/factory/hooksFactory.js
=> Server redirect and client errors

.changeset/eight-keys-happen.md, packages/dev-utils/src/compileErrorParser/index.ts
=> Fixed detection of default webpack compile errors

.changeset/selfish-eels-call.md, packages/server/lib/factory/IMAInternalFactory.js
=> Revert "fix: use res.locals instead of res."

.changeset/itchy-kiwis-arrive.md, docs/cli/cli.md, packages/cli/src/commands/dev.ts, packages/cli/src/types.ts
=> Added ability to customize open URL

.changeset/nasty-rockets-approve.md, packages/server/lib/factory/IMAInternalFactory.js
=> Fixed dummyApp language error on applications that don't support 'en' language

.changeset/tasty-avocados-roll.md, packages/cli/src/webpack/plugins/ManifestPlugin/index.ts
Fixes https://github.com/seznam/ima/issues/455
=> Fixed issue where ManifestPlugin produced manifest.json file without client assets

.changeset/empty-rivers-doubt.md, packages/server/lib/factory/hooksFactory.js
=> Fixed issue where server redirect showed ErrorOverlay in debug mode

.changeset/warm-mice-retire.md, .gitignore, docs/cli/compiler-features.md, packages/cli/src/webpack/languages.ts, packages/core/src/dictionary/Dictionary.ts, packages/core/src/dictionary/MessageFormatDictionary.ts, packages/core/src/index.ts, packages/create-ima-app/template/common/server/template/400.ejs, packages/create-ima-app/template/common/server/template/500.ejs, packages/create-ima-app/template/js/jsconfig.json, packages/create-ima-app/template/ts/tsconfig.json, packages/react-page-renderer/src/component/AbstractComponent.ts, packages/react-page-renderer/src/component/AbstractPureComponent.ts, packages/react-page-renderer/src/componentHelpers.ts
=> Added autocompletion support for language file keys in localization functions

.changeset/eighty-days-vanish.md, packages/react-page-renderer/hook/server.ts
=> fix: clear response viewAdapter for error and before next response

.changeset/shaggy-books-approve.md, packages/react-page-renderer/src/renderer/PageRendererFactory.ts
This method check Component, but the prototype was handed over
=> fix bad parameter to check if component is function

.changeset/tough-pigs-accept.md, packages/core/src/storage/CookieStorage.ts, packages/core/src/storage/__tests__/CookieStorageSpec.ts
add option to create partitioned cookie
https://developer.chrome.com/en/docs/privacy-sandbox/chips/
=> partitioned cookie option

.changeset/purple-peaches-heal.md, package-lock.json, packages/server/package.json
support for defining custom metrics
=> Updates dependency @esmj/monitor to the latest version

.changeset/heavy-readers-flow.md, packages/core/src/router/StaticRoute.ts, packages/core/src/router/__tests__/StaticRouteSpec.ts
=> Fixes router looping for specific request path and routes with more optional parameters

.changeset/pink-beers-appear.md, docs/plugins/plugin-api.md, packages/helpers/src/__tests__/indexSpec.js, packages/helpers/src/index.js, packages/helpers/types.d.ts
Ticket: https://youtrack.seznam.net/issue/CNB-1367/Uprava-IMA-umoznit-skaldani-helpers-pro-pole-jako-concatovani
=> CNB-1367 Uprava IMA, umoznit skaldani helpers pro pole jako concatovani

.changeset/sixty-mangos-listen.md, docs/basic-features/data-fetching.md, packages/core/src/http/HttpAgent.ts, packages/core/src/http/HttpAgentImpl.ts, packages/core/src/http/__tests__/HttpAgentImplSpec.ts
Add option for caching failed requests to prevent mishmashdom errors
=> Add option for caching failed requests

.changeset/perfect-terms-tickle.md, packages/core/src/event/Observable.ts, packages/core/src/event/ObservableImpl.ts, packages/core/src/event/__tests__/ObservableSpec.ts, packages/core/src/types.ts
How are `Utils` typed, fix the typing on the abstract class methods, etc.
=> observable-event-type Change Observable to follow Dispatcher pattern more closely

docs/basic-features/seo-and-meta-manager.md
https://youtrack.seznam.net/issue/USA-3971/IMA-doplneni-do-MetaManageru
=> Update docs - MetaManager & Open redirect
