packages/core/src/page/renderer/ViewAdapter.js
Added method to ViewAdapter that can be overriden to redefine context
value without defining you own new Contenxt and AbstractComponent.
=> refactor: 💡 Eazy context value override

package.json, packages/core/src/storage/CookieStorage.js
Edge not support max date value so I revert to previous safe value
=> fix: 🐛 cookie max expire date for Edge

packages/core/src/router/AbstractRouter.js
getCurrentRouteInfo returns not-found instead exception if not-found
route is set
BREAKING CHANGE: getCurrentRouteInfo returns not-found instead exception if not-found
route is set
=> fix: 🐛 getCurrentRouteInfo returns not-found instead exception

lerna.json, packages/core/package-lock.json, packages/devtools-scripts/.npmignore, packages/devtools-scripts/.npmrc, packages/devtools-scripts/package.json
- devtools-scripts are now properly included in lerna while devtools still being excluded as intended
- added .npmignore so built package contains correct files
=> Devtools-scripts build process fix

packages/core/src/page/handler/PageNavigationHandler.js, packages/core/src/page/handler/__tests__/PageNavigationHandlerSpec.js
We need to use replaceState instead of pushState for redirects to be able to go back in history properly afterwards.
=> fix: use replaceState for redirects instead of pushState

packages/core/package-lock.json, packages/core/src/router/Route.js, packages/core/src/router/__tests__/RouteSpec.js
query parameters that cant be parsed will be replaced with empty string
=> fix: query params parse

packages/core/src/__tests__/NamespaceSpec.js, packages/core/src/namespace.js
The getter or namespace checks path argument for valid string before
performing path splitting. Getter logs error in Debug mode if path is
not type of string and returns undefined. Method has therefore returns
false on invalid path argument.
=> fix: 🐛 namespace.get now checks path type before split

packages/core/src/page/AbstractComponent.js, packages/core/src/page/AbstractPureComponent.js
Fire method sends data=undefined as default to allow object destructing
with default values in event callback argument
=> fix: 🐛 component fire method send data undefined by default

package.json
Reverts changes implemented in https://github.com/seznam/ima/commit/b4104cdd78a49c18d9a3196d9bac8e8cc86ecb99, which causes update of package-lock during publishing.
=> chore: 🤖 Fixed postinstall

docs/docs/page-state.md, packages/core/src/controller/AbstractController.js, packages/core/src/controller/Controller.js, packages/core/src/controller/ControllerDecorator.js, packages/core/src/extension/AbstractExtension.js, packages/core/src/extension/Extension.js, packages/core/src/page/state/PageStateManager.js, packages/core/src/page/state/PageStateManagerImpl.js, packages/core/src/page/state/__tests__/PageStateManagerImplSpec.js
Ability to queue state patches and then commit them as a one to the
original state.
For use cases where you'd in you workflow call `setState` method multiple times or you'd have to collect state patches in a separate variable (this is hard to do across multiple methods).
1. Transaction is initiated with `beginTransaction()` method (or `beginStateTransaction()` in Controller/Extension).
2. From now on every `setState` call is queued and doesn't change the state or re-render anything.
3. Queue is applied with `commitTransaction()`/`commitStateTransaction()` method or emptied with `cancelTransaction()`/`cancelStateTransaction()` method.
=> feat: 🎸 state transactions

packages/core/src/page/manager/AbstractPageManager.js, packages/core/src/page/manager/__tests__/AbstractPageManagerSpec.js
`update()` method of extension receives full page state extended by
partial state from controller and previous extensions
✅ Closes: #101
=> fix: 🐛 extension update method receives full state

packages/core/package-lock.json, packages/core/src/router/AbstractRouter.js, packages/core/src/router/__tests__/AbstractRouterSpec.js, packages/gulp-tasks/package-lock.json, packages/server/package-lock.json
When not-found or error route is handled instead of original route all
former params were lost. This caused trouble when params contained
application-wide info that was required even for the not-found or error
page.
=> fix: 🐛 passing original params to not-found and error route

packages/core/src/router/Response.js, packages/core/src/router/Router.js, packages/core/src/router/ServerRouter.js, packages/core/src/router/__tests__/ResponseSpec.js, packages/core/src/router/__tests__/ServerRouterSpec.js, packages/server/lib/clientApp.js
The `Response.redirect` method now can set not only HTTP status, but
also any arbitrary headers.
=> feat: 🎸 Enable setting headers for redirects

packages/core/src/config/bind.js, packages/core/src/http/HttpAgentImpl.js, packages/core/src/http/__tests__/HttpAgentImplSpec.js
BREAKING CHANGE: 🧨 HttpAgent feature internalCacheOfPromise returns cloned response
=> fix: 🐛 Clone HttpAgent internalCacheOfPromise result

package-lock.json, packages/dev-utils/package.json, packages/dev-utils/src/cliUtils.ts, packages/dev-utils/src/sourceMapUtils.ts, packages/error-overlay/package.json, packages/error-overlay/src/entities/SourceStorage.ts, packages/error-overlay/src/hooks/useConnect.ts, packages/error-overlay/webpack.config.js
Fixes issues with node18 parsing errors and eliminates the need to
handle wasm initcialization
=> fix: 🐛 Replaced source-map with source-map-js

packages/cli/src/plugins/less-constants/LessConstantsPlugin.ts, packages/cli/src/types.ts, packages/cli/src/webpack/config.ts, packages/cli/src/webpack/utils.ts
- Fixed code splitting for dynamic imports
- SWC minimizer now made default since it produces same bundle sizes as terser and is much faster
- Improved swc config to compile to es6 modules and fixed preset-env config (now it only compiles bugfixes in supported syntaxes -> this for example results in optional chaining no longer being always compiled but only few cases that dont work for targeted environments)
- **enables tree shaking**
=> feat: 🎸 Improved code splitting and swc config

docs/docs/routing.md, docs/tutorial/fetching-the-data-from-the-server.md, docs/tutorial/final-polish.md, docs/tutorial/static-view.md, packages/core/src/page/handler/PageNavigationHandler.js, packages/core/src/router/AbstractRouter.js, packages/core/src/router/__tests__/AbstractRouterSpec.js
We discovered a problem, where URL redirects kept throwing 404 error. To fix it, we need to make 2 changes in the core.
1. set the url in `action` object to where we want to be redirected, instead of where we currently are
2. remove part of condition in `PageManagerHandler` checking for error type.
I also fixed the snippet about middleware and corrected few typos.
=> Fix redirect

utils/scripts/utils/utils.js
The index was being passed as an `options` parameter to `rmSync` causing an error of `npm run dev ... -- --init`
=> Fix rmSync in initApp

.changeset/curvy-shoes-compete.md, packages/plugin-cli/src/transformers/swcTransformer.ts
Fixed issue where swcTransformer didn't transform jsx filenames to js extension
=> Fixed issue where swcTransformer didn't transform jsx filenames to js extension

.changeset/popular-rice-approve.md, createWebpackConfig.js, docs/cli/compiler-features.md, docs/cli/ima.config.js.md, packages/cli/src/types.ts, packages/cli/src/webpack/config.ts, packages/cli/src/webpack/utils.ts, packages/create-ima-app/template/package.json
- 3rd party dependencies are no longer processed through swc (except anything under `@ima` namespace).
- this can be extended using custom path regexps in the newly added `transformVendorPaths` ima.config.js option.
- additionaly I have disabled inclusion of `shippedProposals`, since this option can be easily enabled on per-project basis and it adds addition 18kB in minified bundle, while it will probably never be used.
=> Reworked build of 3rd party dependencies

.changeset/blue-poets-fold.md, packages/server/lib/factory/environmentFactory.js
Fix not set $Language in dev environment.
For $Languages we do not want to merge production and dev settings. I think thats why in environmentFactory $Languages is preserving its value. But if $Languages is not set in dev it does not make sense.
=> Fix dev empty language

.changeset/happy-hounds-kiss.md, packages/core/jest.config.js, packages/core/src/__tests__/reviveClientAppSpec.ts, packages/core/src/http/__tests__/HttpProxySpec.ts, packages/core/src/page/handler/__tests__/PageNavigationHandlerSpec.ts, packages/core/src/page/manager/__tests__/ClientPageManagerSpec.ts, packages/core/src/router/__tests__/ClientRouterSpec.ts, packages/create-ima-app/template/app/config/bind.js, packages/create-ima-app/template/server/app.js, packages/react-page-renderer/package.json
Explanation:
```
"exports": {
// Import of index file
// import { ServerPageRenderer } from '@ima/react-page-renderer'
".": {
"node": {
"import": "./dist/esm/server/index.js",
"require": "./dist/cjs/index.js"
},
"default": "./dist/esm/client/index.js"
},
// Shortcut for renderers
"./renderer/*": {
"node": {
"import": "./dist/esm/server/renderer/*.js",
"require": "./dist/cjs/renderer/*.js"
},
"default": "./dist/esm/client/renderer/*.js"
},
// Shortcut for hooks
"./hook/*": "./dist/hook/*.js",
// Backwards compatibility
"./*": "./*.js"
},
```
With IMA 19 we can drop backwards compatibility and change exports to something like this.
```
"exports": {
// Import of index file
".": {
"node": {
"import": "./dist/esm/server/index.js",
"require": "./dist/cjs/index.js"
},
"default": …
```
=> fix: add exports definition with backwards compatibility

.changeset/large-seas-watch.md, packages/cli/src/webpack/plugins/ManifestPlugin/index.ts
Ignore css files from /app/public/css/*.css to be generated in manifest.json.
=> fix: css files generated in manifest are from static/css folder

.changeset/honest-pianos-hope.md, packages/core/src/cache/CacheImpl.ts, packages/core/src/config/bind.ts, packages/core/src/oc/ObjectContainer.ts, packages/core/src/oc/__tests__/ObjectContainerSpec.ts
The ObjectContainer throw new error if dependency of dependencies for class constructor is undefined.
=> ObjectContainer throw error for undefined dependency

.changeset/brown-eggs-begin.md, packages/core/src/boot.ts
Version might be defined already in Environment. So duplicited definition is required
=> Make Version settings optional

.changeset/little-socks-jump.md, packages/server/lib/factory/__tests__/__snapshots__/responseUtilsFactorySpec.js.snap, packages/server/lib/factory/utils/__tests__/__snapshots__/resourcesUtilsSpec.js.snap, packages/server/lib/factory/utils/resourcesUtils.js
according to https://validator.w3.org/nu/#textarea
valid values for `async` are:
- no value
- empty string (= no value via `setAttribute`)
- "async"
=> async attribute should have no value

docs/basic-features/extensions.md
Add missing detail about state keys in extensions - extension doesn't need to declare keys created by itself.
=> readme-extension-state-keys Add info
